const GAMES=window.GAMES||[];
const STATS=window.STATS||{count:GAMES.length,hours:0,unplayed:0,under2:0};
const TIER_LABEL={must:'MUST PLAY',taste:'Definitely your taste',try:'Try it',skip:'Probably skip',played:'Played enough'};
const $=s=>document.querySelector(s);
const state={tab:'must',angle:0,result:null,favs:new Set(JSON.parse(localStorage.getItem('sbpFavs')||'[]')),history:JSON.parse(localStorage.getItem('sbpHistory')||'[]')};
function img(g){return `https://cdn.cloudflare.steamstatic.com/steam/apps/${g.appid}/header.jpg`}
function fmtHours(h){if(!h)return 'Unplayed'; if(h<1)return `${Math.max(1,Math.round(h*60))}m`; return `${h.toFixed(h<10?1:0)}h`}
function tierCounts(){let o={all:GAMES.length};for(const g of GAMES)o[g.tier]=(o[g.tier]||0)+1;return o}
function matchesPlay(g,v){return v==='all'||(v==='unplayed'&&g.hours===0)||(v==='under2'&&g.hours<2)||(v==='under5'&&g.hours<5)||(v==='under10'&&g.hours<10)}
function currentPool(){let min=+$('#ratingFilter').value||0, pf=$('#playFilter').value, tf=$('#tierFilter').value;return GAMES.filter(g=>g.wheelEligible&&matchesPlay(g,pf)&&(g.rating==null||g.rating>=min)&&(tf==='all'||g.tier===tf)&&(!$('#favoritesOnly').checked||state.favs.has(g.appid))&&(!$('#coopOnly').checked||g.coop));}
function weightedSample(arr,n){if(arr.length<=n)return [...arr];let pool=[...arr],out=[];while(out.length<n&&pool.length){let weights=pool.map(g=>$('#weighted').checked?Math.max(4,g.score-45):1);let total=weights.reduce((a,b)=>a+b,0),r=Math.random()*total,idx=0;for(;idx<pool.length;idx++){r-=weights[idx];if(r<=0)break}out.push(pool.splice(Math.min(idx,pool.length-1),1)[0]);}return out}
function wheelGames(){return weightedSample(currentPool(),+$('#wheelSize').value)}
let visibleWheel=[];
function drawWheel(){visibleWheel=wheelGames();let c=$('#wheel'),ctx=c.getContext('2d'),W=c.width,H=c.height,cx=W/2,cy=H/2,R=W*.47;ctx.clearRect(0,0,W,H);if(!visibleWheel.length){ctx.fillStyle='#13202a';ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fill();ctx.fillStyle='#91a9ba';ctx.textAlign='center';ctx.font='700 28px system-ui';ctx.fillText('No games match filters',cx,cy);return}let n=visibleWheel.length,step=Math.PI*2/n;for(let i=0;i<n;i++){let a0=-Math.PI/2+i*step,a1=a0+step;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,R,a0,a1);ctx.closePath();let hue=196+(i%6)*7;ctx.fillStyle=`hsl(${hue} 45% ${18+(i%2)*5}%)`;ctx.fill();ctx.strokeStyle='#335369';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(cx,cy);ctx.rotate(a0+step/2);ctx.textAlign='right';ctx.fillStyle='#eaf6ff';ctx.font=`700 ${n>30?13:n>20?15:18}px system-ui`;let label=visibleWheel[i].name;let max=n>30?25:34;if(label.length>max)label=label.slice(0,max-1)+'…';ctx.fillText(label,R-20,6);ctx.restore()}}
function spin(){if(!visibleWheel.length)return;$('#spin').disabled=true;$('#result').classList.remove('show');let idx=Math.floor(Math.random()*visibleWheel.length);if($('#weighted').checked){let weights=visibleWheel.map(g=>Math.max(4,g.score-45)),total=weights.reduce((a,b)=>a+b,0),r=Math.random()*total;idx=0;for(;idx<weights.length-1;idx++){r-=weights[idx];if(r<=0)break}}
 let step=360/visibleWheel.length,target=360-(idx*step+step/2),extra=360*(5+Math.floor(Math.random()*3)),start=state.angle,end=start+extra+((target-(start%360)+360)%360),dur=4300,t0=performance.now();function ease(t){return 1-Math.pow(1-t,4)}function frame(now){let p=Math.min(1,(now-t0)/dur);state.angle=start+(end-start)*ease(p);$('#wheel').style.transform=`rotate(${state.angle}deg)`;if(p<1)requestAnimationFrame(frame);else{state.angle=end;choose(visibleWheel[idx]);$('#spin').disabled=false}}requestAnimationFrame(frame)}
function choose(g){state.result=g;$('#resultImg').src=img(g);$('#resultImg').onerror=e=>e.currentTarget.style.visibility='hidden';$('#resultName').textContent=g.name;$('#resultMeta').textContent=`${fmtHours(g.hours)} · ${g.rating?g.rating.toFixed(2)+'%':'No rating'} · ${TIER_LABEL[g.tier]}${g.coop?' · co-op hint':''}`;$('#result').classList.add('show');state.history.unshift({appid:g.appid,name:g.name,at:new Date().toISOString()});state.history=state.history.slice(0,30);localStorage.setItem('sbpHistory',JSON.stringify(state.history));renderHistory()}
function renderTabs(){let c=tierCounts(),tabs=[['must','MUST PLAY'],['taste','YOUR TASTE'],['try','TRY'],['skip','SKIP'],['played','PLAYED ENOUGH'],['all','ALL']];$('#tabs').innerHTML=tabs.map(([k,v])=>`<button class="tab ${state.tab===k?'active':''}" data-tab="${k}">${v} · ${c[k]||0}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderTabs();renderList()})}
function filteredList(){let q=$('#search').value.trim().toLowerCase();return GAMES.filter(g=>(state.tab==='all'||g.tier===state.tab)&&(!q||g.name.toLowerCase().includes(q))).sort((a,b)=>b.score-a.score||((b.rating||0)-(a.rating||0)))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderList(){let arr=filteredList();$('#list').innerHTML=arr.length?arr.map(g=>`<div class="game"><img class="cover" loading="lazy" src="${img(g)}" onerror="this.style.visibility='hidden'"><div><div class="gtitle">${esc(g.name)}</div><div class="sub"><span class="badge ${g.tier}">${TIER_LABEL[g.tier]}</span>${g.coop?' · 👥 co-op hint':''}</div></div><div class="hours">${fmtHours(g.hours)}</div><div class="rating">${g.rating?g.rating.toFixed(1)+'%':'—'}</div><div class="score">${g.score}</div><button class="star ${state.favs.has(g.appid)?'on':''}" data-id="${g.appid}" title="Favorite">★</button></div>`).join(''):`<div class="empty">Nothing here.</div>`;document.querySelectorAll('.star').forEach(b=>b.onclick=()=>{let id=+b.dataset.id;state.favs.has(id)?state.favs.delete(id):state.favs.add(id);localStorage.setItem('sbpFavs',JSON.stringify([...state.favs]));b.classList.toggle('on');updateWheel()})}
function renderHistory(){let h=state.history;$('#historyList').innerHTML=h.length?h.map(x=>`<div class="history-row"><span>${esc(x.name)}</span><small>${new Date(x.at).toLocaleString()}</small></div>`).join(''):'<div class="empty">No spins yet.</div>'}
function updateStats(){let pool=currentPool();$('#sGames').textContent=STATS.count.toLocaleString();$('#sHours').textContent=STATS.hours.toLocaleString(undefined,{maximumFractionDigits:1});$('#sUnplayed').textContent=STATS.unplayed.toLocaleString();$('#sPool').textContent=pool.length.toLocaleString();$('#poolText').textContent=`${pool.length} eligible games · wheel samples up to ${$('#wheelSize').value} each spin.`}
function updateWheel(){updateStats();drawWheel()}
['playFilter','ratingFilter','tierFilter','wheelSize','favoritesOnly','coopOnly','weighted'].forEach(id=>$('#'+id).addEventListener('change',updateWheel));$('#ratingFilter').addEventListener('input',updateWheel);$('#search').addEventListener('input',renderList);$('#spin').onclick=spin;$('#reroll').onclick=()=>{drawWheel();spin()};$('#openSteam').onclick=()=>state.result&&window.open(`https://store.steampowered.com/app/${state.result.appid}/`,'_blank');$('#resetBtn').onclick=()=>{$('#search').value='';state.tab='must';renderTabs();renderList()};$('#historyBtn').onclick=()=>{$('#historyModal').classList.add('show');renderHistory()};$('#closeHistory').onclick=()=>$('#historyModal').classList.remove('show');$('#historyModal').onclick=e=>{if(e.target.id==='historyModal')$('#historyModal').classList.remove('show')};$('#clearHistory').onclick=()=>{state.history=[];localStorage.removeItem('sbpHistory');renderHistory()};
renderTabs();renderList();renderHistory();updateWheel();
